#ifndef _SHADER_DVAR_DEFINES_H_
#define _SHADER_DVAR_DEFINES_H_

// r_materialViz
#define PG_DEBUG_MTL_ALBEDO 1
#define PG_DEBUG_MTL_NORMAL 2
#define PG_DEBUG_MTL_ROUGHNESS 3
#define PG_DEBUG_MTL_METALNESS 4
#define PG_DEBUG_MTL_GEOM_NORMAL 5
#define PG_DEBUG_MTL_GEOM_TANGENT 6
#define PG_DEBUG_MTL_GEOM_BITANGENT 7

// r_lightingViz
#define PG_DEBUG_LIGHTING_DIRECT 1
#define PG_DEBUG_LIGHTING_INDIRECT 2
#define PG_DEBUG_LIGHTING_DIFFUSE_INDIRECT 3
#define PG_DEBUG_LIGHTING_SPECULAR_INDIRECT 4

// r_skyboxViz
#define PG_DEBUG_SKY_REGULAR 0
#define PG_DEBUG_SKY_IRRADIANCE 1
#define PG_DEBUG_SKY_BLACK 2
#define PG_DEBUG_SKY_WHITE 3


#endif // #ifndef _SHADER_DVAR_DEFINES_H_