function( SET_TARGET_COMPILE_OPTIONS_DEFAULT )
    foreach(arg IN LISTS ARGN)
        if(UNIX AND NOT APPLE)
            target_compile_options(${arg} PUBLIC -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-switch -Wno-format)
            target_compile_options(${arg} PUBLIC $<$<CONFIG:DEBUG>: -g>)
            target_compile_options(${arg} PUBLIC $<$<CONFIG:RELEASE>: -O2>)
            target_compile_options(${arg} PUBLIC $<$<CONFIG:SHIP>:-O3>)
        elseif(MSVC)
            target_compile_options(${arg} PUBLIC $<$<CONFIG:DEBUG>: /Od /Oi>)
            target_compile_options(${arg} PUBLIC $<$<CONFIG:RELEASE>: /O2 /Zi /Oi /GL /Ot>)
            target_compile_options(${arg} PUBLIC $<$<CONFIG:SHIP>: /O2 /Oi /GL /Ot>)
            target_compile_options(${arg} PRIVATE /MD)
            target_compile_options(${arg} PRIVATE /MP)
            target_link_options(${arg} PUBLIC $<$<CONFIG:RELEASE>: /DEBUG /LTCG>)
            target_link_options(${arg} PUBLIC $<$<CONFIG:SHIP>: /LTCG>)
            target_compile_definitions(${arg} PRIVATE -D_CRT_SECURE_NO_WARNINGS )#-D_ITERATOR_DEBUG_LEVEL=0)
        endif()
    endforeach()
endfunction()
